# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialize.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

In [7]:
%run initialise.py

Exception: File `'initialise.py'` not found.

#### 1. Import the numpy package under the name `np` (★☆☆)

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [9]:
print(np.__version__)

1.20.1


#### 3. Create a null vector of size 10 (★☆☆)

In [4]:
x= np.zeros(10)

#### 4. How to find the memory size of any array (★☆☆)

In [27]:
x.size

10

#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [2]:
x= np.zeros(10)
x[5]=10

#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [6]:
y=np.arange(10,50)
print(y)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [7]:
y=y[::-1]
print(y)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [12]:
z=np.arange(0,9).reshape(3,3)
print(z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [26]:
v=np.array([1,2,0,0,4,0])
print(np.where(v!=0))

(array([0, 1, 4], dtype=int64),)


#### 11. Create a 3x3 identity matrix (★☆☆)

In [38]:
w= np.identity(3)
print(w)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆)

In [31]:
u=np.random.rand(3,3,3)
print(u)

[[[0.54220762 0.21382201 0.31192706]
  [0.539637   0.62710668 0.83928037]
  [0.57362734 0.38569054 0.40110508]]

 [[0.0663991  0.40658856 0.77963932]
  [0.05672091 0.98388332 0.42428344]
  [0.80080728 0.41520489 0.9417449 ]]

 [[0.05728299 0.18908187 0.54897087]
  [0.57178575 0.35649911 0.82681506]
  [0.98836582 0.16886607 0.65823234]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [38]:
k=np.random.rand(10,10)
print(k.min(),k.max())

0.010465686752624381 0.9640290265969533


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [41]:
a=np.random.rand(30)
print(a.mean())

0.46985565414534847


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [20]:
b=np.ones((5,5))
b[1:-1,1:-1]=0
print(b)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [21]:
b=np.pad(b,pad_width=1,mode='constant',constant_values=0)
print(b)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [22]:
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1

False

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [113]:
c=np.diag([1,2,3,4])
d=np.vstack((np.array([0,0,0,0]),c))
e=np.column_stack((d,np.array([0,0,0,0,0])))
print(e)
#or
r=np.diag(np.arange(4)+1,k=-1)
print(r)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]
[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [169]:
a=np.zeros((8,8))
a[1::2,::2]=1
a[::2,1::2]=1
print(a)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [12]:
m=np.arange(0,336).reshape(6,7,8)
print(np.where(m==99))

(array([1], dtype=int64), array([5], dtype=int64), array([3], dtype=int64))


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [178]:
t=np.array([[0,1],[1,0]])
print(np.tile(t,(4,4)))

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [182]:
s=np.random.rand(5,5)
print(s)
s=(s-s.min())/(s.max()-s.min())
print(s)

[[0.98349842 0.10218845 0.41671974 0.08629112 0.55825925]
 [0.0683429  0.4159983  0.28122222 0.82601502 0.21354277]
 [0.26031877 0.28874133 0.34568467 0.76361221 0.13396834]
 [0.28836976 0.95222746 0.71161021 0.40257266 0.14324029]
 [0.07853357 0.48193951 0.00359759 0.80772876 0.81496177]]
[[1.         0.1006131  0.42159588 0.08438969 0.56603857]
 [0.06607332 0.42085964 0.28331911 0.83928639 0.21425145]
 [0.2619869  0.29099245 0.34910377 0.77560361 0.13304484]
 [0.29061325 0.96808763 0.72253497 0.40715862 0.14250697]
 [0.07647302 0.48815339 0.         0.82062505 0.82800642]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [15]:
color = np.dtype([("r", np.ubyte),("g", np.ubyte),("b", np.ubyte),("a", np.ubyte)])         

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [188]:
a1=np.random.rand(5,3)
a2=np.random.rand(3,2)
a3=np.dot(a1,a2)
print(a1,a2,a3)

[[0.20483071 0.21287711 0.75773059]
 [0.36646785 0.73552192 0.45806591]
 [0.18654684 0.40939842 0.09751574]
 [0.65187481 0.2747358  0.77191029]
 [0.44527056 0.70827949 0.53161927]] [[0.47662829 0.80814894]
 [0.65034342 0.70796233]
 [0.45068043 0.42920381]] [[0.57756569 0.64146356]
 [0.85945212 1.01348605]
 [0.3991115  0.48245041]
 [0.83725946 1.05262137]
 [0.91244385 1.08945314]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [5]:
p=np.random.rand(20)
p[3:8]=np.negative(p[3:8])
print(p)

[ 0.93408201  0.17813089  0.82963692 -0.53379951 -0.21660368 -0.77508295
 -0.51181457 -0.27156212  0.23955128  0.78069496  0.8430943   0.46281731
  0.77382209  0.3958858   0.22085707  0.35528901  0.78220471  0.52690943
  0.96452663  0.88788034]


#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [31]:
9
10

10

#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [16]:
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z

NameError: name 'Z' is not defined

#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [20]:
g=np.array(0)
h=np.array([np.nan]).astype(int).astype(float)
print(g//g,h)

0 [-2.14748365e+09]


<ipython-input-20-961dcd252a8f>:3: RuntimeWarning: divide by zero encountered in floor_divide
  print(g//g,h)


#### 29. How to round away from zero a float array ? (★☆☆)

In [22]:
q=np.random.rand(20)
print(q,np.round(q,0))

[0.99189643 0.33926546 0.28405355 0.93881937 0.74531342 0.21603299
 0.82792206 0.07209393 0.51574034 0.87395661 0.96267337 0.26972967
 0.42411784 0.04743558 0.9219354  0.9921384  0.17914775 0.88777033
 0.16451323 0.5914458 ] [1. 0. 0. 1. 1. 0. 1. 0. 1. 1. 1. 0. 0. 0. 1. 1. 0. 1. 0. 1.]


#### 30. How to find common values between two arrays? (★☆☆)

In [24]:
d=np.arange(0,10)
b=np.array([5,8,7,89,1])
print(np.intersect1d(d,b))

[1 5 7 8]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [ ]:
defaults = np.seterr(all="ignore")
Z = np.ones(1) / 0

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [27]:
np.sqrt(-1) == np.emath.sqrt(-1)

<ipython-input-27-16339fbc685e>:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1) == np.emath.sqrt(-1)


False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [44]:
import datetime 
tod=datetime.date.today()
tom=tod+datetime.timedelta(days=1)
yes=tod-datetime.timedelta(days=1)
print('today:',tod,'tomarrow:',tom,'yesterday:',yes)

today: 2021-08-29 tomarrow: 2021-08-30 yesterday: 2021-08-28


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [32]:
dates=np.arange('2016-07','2016-08',dtype='datetime64[D]')
print(dates)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [39]:
A=np.arange(0,9).reshape(3,3)
B=np.arange(14,23).reshape(3,3)
np.add(A,B,out=B)
np.negative(A,out=A)
np.multiply(A,B,out=A)
print(A/2)

[[   0.   -8.  -18.]
 [ -30.  -44.  -60.]
 [ -78.  -98. -120.]]


#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [44]:
q=np.random.uniform(0,10,20)
print(q,np.round(q,0))
print(np.floor(q))
print(np.floor(q))print(np.floor(q))

[2.01993397 0.23974688 5.0753803  7.62306496 2.08144827 7.69707493
 6.80790121 3.88342459 6.21965114 0.55740603 5.11797706 8.38455301
 4.0495134  8.6252661  7.14211739 2.20443065 7.22801335 4.88167415
 8.56680729 5.1579746 ] [2. 0. 5. 8. 2. 8. 7. 4. 6. 1. 5. 8. 4. 9. 7. 2. 7. 5. 9. 5.]
[2. 0. 5. 7. 2. 7. 6. 3. 6. 0. 5. 8. 4. 8. 7. 2. 7. 4. 8. 5.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [47]:
d=np.arange(0,5)
print(np.tile(d,(4,1)))

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [14]:
def function():
    for x in range(10):
        yield x
b=np.array(list(function()))
print(b)

[0 1 2 3 4 5 6 7 8 9]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [27]:
c=np.linspace(0,1,11,endpoint=False)[1:]
print(c)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 40. Create a random vector of size 10 and sort it (★★☆)

In [36]:
d=np.random.randint(1,7,10)
print(d,np.sort(d))

[3 5 1 3 6 5 6 2 3 1] [1 1 2 3 3 3 5 5 6 6]


#### 41. How to sum a small array faster than np.sum? (★★☆)

In [37]:
d=np.random.randint(1,7,10)
print(np.add.reduce(d))

34


#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [43]:
A=np.random.rand(10)
B=np.random.rand(10)
print(np.allclose(A,B))
print(np.array_equal(A,B))

False
False


#### 43. Make an array immutable (read-only) (★★☆)

In [50]:
A=np.random.rand(10)
A.flags.writeable=False
print(A)
A[1]=1

[0.3647417  0.13338802 0.02458761 0.11280708 0.28738126 0.80585655
 0.64324544 0.8431352  0.93328524 0.31989697]


ValueError: assignment destination is read-only

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [79]:
c=np.random.randint(1,50,20).reshape((10,2))
x=c[:,0]
y=c[:,1]
r=np.sqrt(x**2+y**2)
t=np.arctan2(y,x)
p=np.dstack((r,t))
print(c,p)

[[36 24]
 [40 23]
 [49 24]
 [10 37]
 [35  3]
 [ 2 19]
 [32  4]
 [ 9 29]
 [40 30]
 [ 7 31]] [[[43.26661531  0.5880026 ]
  [46.14108798  0.52183428]
  [54.56189146  0.45545107]
  [38.32753579  1.3068326 ]
  [35.12833614  0.08550529]
  [19.10497317  1.46591939]
  [32.24903099  0.12435499]
  [30.3644529   1.26987609]
  [50.          0.64350111]
  [31.78049716  1.34871442]]]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [86]:
A=np.random.rand(10)
print(A)
A[A.argmax()]=0
print(A)

[0.38979319 0.01327955 0.0440646  0.616737   0.80819196 0.30725781
 0.23856521 0.37804818 0.90105654 0.27299556]
[0.38979319 0.01327955 0.0440646  0.616737   0.80819196 0.30725781
 0.23856521 0.37804818 0.         0.27299556]


#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

In [121]:
s=np.linspace(0,1,3)
s3=np.zeros((3,3),[('x',float),('y',float)])
s3['x'],s3['y']= np.meshgrid(s,s)
print(s3)

[[(0. , 0. ) (0.5, 0. ) (1. , 0. )]
 [(0. , 0.5) (0.5, 0.5) (1. , 0.5)]
 [(0. , 1. ) (0.5, 1. ) (1. , 1. )]]


#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

In [144]:
x=np.arange(10)
y=x+10
x1=np.tile(x,(10,1))
y1=np.tile(y,(10,1)).transpose()
c=1/(x1-y1)
print(c)

[[-0.1        -0.11111111 -0.125      -0.14285714 -0.16666667 -0.2
  -0.25       -0.33333333 -0.5        -1.        ]
 [-0.09090909 -0.1        -0.11111111 -0.125      -0.14285714 -0.16666667
  -0.2        -0.25       -0.33333333 -0.5       ]
 [-0.08333333 -0.09090909 -0.1        -0.11111111 -0.125      -0.14285714
  -0.16666667 -0.2        -0.25       -0.33333333]
 [-0.07692308 -0.08333333 -0.09090909 -0.1        -0.11111111 -0.125
  -0.14285714 -0.16666667 -0.2        -0.25      ]
 [-0.07142857 -0.07692308 -0.08333333 -0.09090909 -0.1        -0.11111111
  -0.125      -0.14285714 -0.16666667 -0.2       ]
 [-0.06666667 -0.07142857 -0.07692308 -0.08333333 -0.09090909 -0.1
  -0.11111111 -0.125      -0.14285714 -0.16666667]
 [-0.0625     -0.06666667 -0.07142857 -0.07692308 -0.08333333 -0.09090909
  -0.1        -0.11111111 -0.125      -0.14285714]
 [-0.05882353 -0.0625     -0.06666667 -0.07142857 -0.07692308 -0.08333333
  -0.09090909 -0.1        -0.11111111 -0.125     ]
 [-0.05555556 -0.05

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

In [145]:
for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)
   print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


#### 49. How to print all the values of an array? (★★☆)

In [148]:
np.set_printoptions(threshold=float("inf"))
x=np.arange(10)
print(x)

[0 1 2 3 4 5 6 7 8 9]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [156]:
m=np.random.rand(10)
n=np.random.uniform(0,1)
print(m,n,m[abs(m-n).argmin()])

[0.08262765 0.37512094 0.95731354 0.38832809 0.26012618 0.78967945
 0.31225302 0.55336566 0.09946436 0.0502434 ] 0.8162395257008492 0.7896794527761457


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [157]:
Z = np.zeros(10, [ ('position', [ ('x', float, 1),
                                  ('y', float, 1)]),
                   ('color',    [ ('r', float, 1),
                                  ('g', float, 1),
                                  ('b', float, 1)])])
print(Z)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


<ipython-input-157-6f1aa4d7a2ff>:1: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  Z = np.zeros(10, [ ('position', [ ('x', float, 1),


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

In [172]:
c=np.arange(20).reshape(10,2)
x=np.atleast_2d(c[:,0])
y=np.atleast_2d(c[:,1])
r=np.sqrt((x-x.T)**2+(y-y.T)**2)
print(c,r)

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]
 [16 17]
 [18 19]] [[ 0.          2.82842712  5.65685425  8.48528137 11.3137085  14.14213562
  16.97056275 19.79898987 22.627417   25.45584412]
 [ 2.82842712  0.          2.82842712  5.65685425  8.48528137 11.3137085
  14.14213562 16.97056275 19.79898987 22.627417  ]
 [ 5.65685425  2.82842712  0.          2.82842712  5.65685425  8.48528137
  11.3137085  14.14213562 16.97056275 19.79898987]
 [ 8.48528137  5.65685425  2.82842712  0.          2.82842712  5.65685425
   8.48528137 11.3137085  14.14213562 16.97056275]
 [11.3137085   8.48528137  5.65685425  2.82842712  0.          2.82842712
   5.65685425  8.48528137 11.3137085  14.14213562]
 [14.14213562 11.3137085   8.48528137  5.65685425  2.82842712  0.
   2.82842712  5.65685425  8.48528137 11.3137085 ]
 [16.97056275 14.14213562 11.3137085   8.48528137  5.65685425  2.82842712
   0.          2.82842712  5.65685425  8.48528137]
 [19.79898987 16.97056275 14.14213562 11.31

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [4]:
z= (np.random.rand(10)*100).astype(np.float32)
y=z.view(np.int32)
y[:] = z
print(z,y)

[0.00e+00 8.27e-44 1.35e-43 6.73e-44 1.23e-43 6.31e-44 1.23e-43 1.02e-43
 9.67e-44 5.61e-44] [ 0 59 96 48 88 45 88 73 69 40]


#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [5]:
from io import StringIO

chars = StringIO('''1, 2, 3, 4, 5

                    6,  ,  , 7, 8

                     ,  , 9, 10, 11
''')
read = np.genfromtxt(chars, delimiter=",", dtype=np.int32,filling_values=0)
print(read)

[[ 1  2  3  4  5]
 [ 6  0  0  7  8]
 [ 0  0  9 10 11]]


#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

In [16]:
b=np.random.rand(10).reshape(5,2)
for i,v in  np.ndenumerate(b):
    print(i,v)
for i in np.ndindex(b.shape):
    print(i,b[i])

(0, 0) 0.8679133836315995
(0, 1) 0.8806790075743737
(1, 0) 0.11791402650787108
(1, 1) 0.21158635453007646
(2, 0) 0.47964082097869964
(2, 1) 0.317983804807525
(3, 0) 0.5386197181788633
(3, 1) 0.14851028978032887
(4, 0) 0.495748641861284
(4, 1) 0.6403520713556766
(0, 0) 0.8679133836315995
(0, 1) 0.8806790075743737
(1, 0) 0.11791402650787108
(1, 1) 0.21158635453007646
(2, 0) 0.47964082097869964
(2, 1) 0.317983804807525
(3, 0) 0.5386197181788633
(3, 1) 0.14851028978032887
(4, 0) 0.495748641861284
(4, 1) 0.6403520713556766


#### 56. Generate a generic 2D Gaussian-like array (★★☆)

In [28]:
x,y=np.meshgrid(np.linspace(-1,1,5),np.linspace(-1,1,5))
s_x,s_y,m_x,m_y=1,1,0,0
g=np.exp(-(((x-m_x)**2)/(2*s_x**2)+((y-m_y)**2)/(2*s_y**2)))
print(g/(2*np.pi*s_x*s_y))

[[0.05854983 0.0851895  0.09653235 0.0851895  0.05854983]
 [0.0851895  0.12394999 0.14045374 0.12394999 0.0851895 ]
 [0.09653235 0.14045374 0.15915494 0.14045374 0.09653235]
 [0.0851895  0.12394999 0.14045374 0.12394999 0.0851895 ]
 [0.05854983 0.0851895  0.09653235 0.0851895  0.05854983]]


#### 57. How to randomly place p elements in a 2D array? (★★☆)

In [42]:
d=np.random.rand(3,3)
p=np.random.randint(0,9)
np.put(d,np.random.choice(range(9), p, replace=False),1)
print(d,p)

[[1.        1.        1.       ]
 [0.0552663 1.        1.       ]
 [1.        1.        1.       ]] 8


#### 58. Subtract the mean of each row of a matrix (★★☆)

In [49]:
h=np.random.rand(3,3)
j=h-h.mean(axis=1).reshape(-1,1)
print(j)

[[-0.12102632  0.03933349  0.08169283]
 [-0.01313208 -0.19355768  0.20668975]
 [ 0.09298265 -0.1159763   0.02299365]]


#### 59. How to sort an array by the nth column? (★★☆)

In [65]:
h=np.random.randint(1,50,(5,5))
print(h)
print(h[h[:,4].argsort()])

[[28 25 14  1 49]
 [41 27 14  2 39]
 [42 13  2 30 23]
 [20 38 24 28 49]
 [ 7 35  2 41 46]]
[[42 13  2 30 23]
 [41 27 14  2 39]
 [ 7 35  2 41 46]
 [28 25 14  1 49]
 [20 38 24 28 49]]


#### 60. How to tell if a given 2D array has null columns? (★★☆)

In [80]:
n=np.random.randint(0,3,(3,9))
print(n,(~n.any(axis=0)).any())

[[0 2 1 2 1 0 0 2 0]
 [2 2 1 2 2 1 0 0 1]
 [0 0 0 2 0 1 1 0 2]] False


#### 61. Find the nearest value from a given value in an array (★★☆)

In [95]:
n=np.random.randint(0,50,10)
p=np.random.randint(0,50)
print(n,p,n.flat[np.abs(n-p).argmin()])

[ 4 28  3  9  0  8 41 46  4 41] 6 4


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

In [100]:
a=np.random.randint(1,20,(1,3))
b=np.random.randint(1,30,(3,1))
c=np.nditer([a,b,None])
for x,y,z in c: z[...] = x + y
print(a,b,c.operands[2])

[[ 3 11 19]] [[ 2]
 [19]
 [22]] [[ 5 13 21]
 [22 30 38]
 [25 33 41]]


#### 63. Create an array class that has a name attribute (★★☆)

In [107]:
class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj=np.asarray(array).view(cls)
        obj.name=name
        return obj
    def __array_finalize__(self,obj):
        if obj is None: return
        self.info = getattr(obj,'name',"no name")
z=NamedArray(np.arange(10),"range_10")
print(z,z.name)

[0 1 2 3 4 5 6 7 8 9] range_10


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

In [6]:
a=np.random.randint(0,20,10)
b=np.ones(10)
print(a)
np.add.at(a,b,1)
print(a)

[ 1 14 13  0 19  9  9  8 18  4]


IndexError: arrays used as indices must be of integer (or boolean) type

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

In [125]:
X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
F = np.bincount(I,X)
print(F)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

In [7]:
w, h = 256, 256
I = np.random.randint(0, 4, (h, w, 3)).astype(np.ubyte)
colors = np.unique(I.reshape(-1, 3), axis=0)
n = len(colors)
print(n)

64


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

In [145]:
a=np.random.randint(0,20,(4,3,5,6))
print(a.sum(axis=(2,3)))

[[324 300 332]
 [298 279 290]
 [250 355 247]
 [233 238 239]]


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

In [147]:
D=np.random.randint(0,10,100)
S=np.random.randint(0,10,100)
import pandas as pd
print(pd.Series(D).groupby(S).mean())

0    3.625000
1    3.454545
2    5.615385
3    4.285714
4    3.777778
5    3.125000
6    5.000000
7    4.500000
8    5.250000
9    4.800000
dtype: float64


#### 69. How to get the diagonal of a dot product? (★★★)

In [152]:
a=np.random.rand(3,3)
b=np.random.rand(3,3)
print(np.diag(np.dot(a,b)))

[0.99708919 2.13446336 0.32656309]


#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

In [161]:
z=np.array([1, 2, 3, 4, 5])
x=np.zeros(3*(len(z)-1)+len(z))
x[::4]=z
print(z,x)

[1 2 3 4 5] [1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

In [168]:
a=np.random.randint(0,50,(5,5,3))
b=np.random.randint(0,50,(5,5))
print(a*b[:,:,None])

[[[  68  408  289]
  [1386  726  462]
  [ 437  304  684]
  [ 900 1410  540]
  [ 812  588  252]]

 [[1472  608  704]
  [ 999  185  370]
  [ 700    0  640]
  [  70  175  220]
  [  84   24  102]]

 [[ 481  247  520]
  [ 510   75  555]
  [ 578  357  136]
  [1131 1872  819]
  [ 425  200  850]]

 [[1568 2009 1519]
  [ 560  532  560]
  [ 760  342  646]
  [ 400    0  800]
  [ 390  330  780]]

 [[ 312  585  559]
  [ 864  816  144]
  [ 119  561   68]
  [1260  405  810]
  [  81  132  111]]]


#### 72. How to swap two rows of an array? (★★★)

In [171]:
b=np.random.randint(0,50,(5,5))
print(b)
b[[0,2]]=b[[2,0]]
print(b)

[[44 41 36 42  8]
 [28 42 12 13 24]
 [18 46 32 19 13]
 [17 15 25  6 34]
 [ 0 20  9 41 26]]
[[18 46 32 19 13]
 [28 42 12 13 24]
 [44 41 36 42  8]
 [17 15 25  6 34]
 [ 0 20  9 41 26]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

In [181]:
v=np.random.randint(0,100,(10,3))
print(v)
w=np.roll(v.repeat(2,axis=1),-1,axis=1)
w=w.reshape(len(w)*3,2)
w=np.sort(w,axis=1)
x=w.view(dtype=[('p0',w.dtype),('p1',w.dtype)])
print(np.unique(x))

[[16 30 77]
 [20 62 37]
 [ 5 25 86]
 [65 92 53]
 [ 8 58 14]
 [44 17 99]
 [55 17 23]
 [88 19 45]
 [84  7 83]
 [ 9 62 20]]
[( 5, 25) ( 5, 86) ( 7, 83) ( 7, 84) ( 8, 14) ( 8, 58) ( 9, 20) ( 9, 62)
 (14, 58) (16, 30) (16, 77) (17, 23) (17, 44) (17, 55) (17, 99) (19, 45)
 (19, 88) (20, 37) (20, 62) (23, 55) (25, 86) (30, 77) (37, 62) (44, 99)
 (45, 88) (53, 65) (53, 92) (65, 92) (83, 84)]


#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

In [186]:
B=np.sort(np.random.randint(1,31,9))
print(B)
C=np.bincount(B)
A=np.repeat(np.arange(len(C)), C)
print(A)

[ 2 12 13 14 15 24 25 27 30]
[ 2 12 13 14 15 24 25 27 30]


#### 75. How to compute averages using a sliding window over an array? (★★★)

In [198]:
def avg(a,n):
    r=np.cumsum(a,dtype=float)
    r[n:]=r[n:]-r[:-n]
    return r[n-1:]/n
print(avg(A,2))

[ 7.  12.5 13.5 14.5 19.5 24.5 26.  28.5]


#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

In [217]:
from numpy.lib import stride_tricks
def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.strides[0], a.strides[0])
    return stride_tricks.as_strided(a, shape=shape, strides=strides)
z=rolling(np.random.randint(0,30,10),3)
print(z)

[[11 18 13]
 [18 13  0]
 [13  0 27]
 [ 0 27 21]
 [27 21 21]
 [21 21  7]
 [21  7 14]
 [ 7 14 18]]


#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

In [204]:
c=np.random.randint(0,2,100)
np.logical_not(c,out=c)
Z=np.random.uniform(-1.0,1.0,100)
np.negative(Z,out=Z)

array([-0.20423216,  0.52633314,  0.08605598,  0.46134612,  0.40484358,
        0.27742029,  0.76259347,  0.65166174, -0.25944307, -0.36937838,
        0.28089457,  0.91399759,  0.09456421, -0.33644578,  0.12142616,
        0.82814436, -0.59341995, -0.59002871, -0.29019914,  0.46096403,
       -0.00695128, -0.52516409, -0.63513303,  0.42790581, -0.58762427,
       -0.69917818, -0.35474239,  0.86578773,  0.01440149,  0.84408663,
       -0.7228319 , -0.99635761, -0.41682851,  0.62049158,  0.82684684,
        0.86904427, -0.36015004,  0.75989286,  0.26338511,  0.08263444,
        0.71103997,  0.20954939, -0.12679547, -0.99659093, -0.94341854,
        0.06240563, -0.98944446, -0.86126574,  0.1163284 ,  0.69995194,
        0.08137675, -0.90587587, -0.66415943,  0.54900558, -0.71509479,
        0.83126014,  0.84044812, -0.83166179,  0.39090784, -0.08748685,
        0.15726242,  0.23577713, -0.42529297, -0.64291922, -0.09897394,
       -0.13900875, -0.2472633 , -0.44073213, -0.99359455,  0.88

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

In [210]:
def dis(p0,p1,p):
    t=p1-p0
    l=(t**2).sum(axis=1)
    u=-((p0[:,0]-p[...,0])*t[:,0] + (p0[:,1]-p[...,1])*t[:,1]) / l
    u=u.reshape(len(u),1)
    d=p0+u*t - p
    return np.sqrt((d**2).sum(axis=1))
p0=np.random.randint(-10,10,(10,2))
p1=np.random.randint(-10,10,(10,2))
p=np.random.randint(-10,10,( 1,2))
print(dis(p0,p1,p))

[ 1.40329283  4.35722405  1.13344497  1.38675049  1.40329283  9.89949494
 10.1597004   2.44587426  2.60472943  4.0309682 ]


#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

In [214]:
p0=np.random.randint(-10,10,(10,2))
p1=np.random.randint(-10,10,(10,2))
p=np.random.randint(-10,10,( 10,2))
print(np.array([dis(p0,p1,p_i)for p_i in p]))

[[ 2.16930458  8.94427191  7.14274933  7.36728736  9.296815    9.89949494
   4.          9.89949494  9.19238816  3.53553391]
 [ 4.98940053  5.36656315  7.14274933  7.89352217  6.31481774  5.65685425
   8.          8.48528137  6.36396103 12.02081528]
 [ 5.31479622 11.18033989  7.00538876  9.1214034  10.34928463 11.3137085
   3.          7.07106781 10.60660172  4.94974747]
 [ 7.48410079  8.94427191  9.8899606  11.48946005  9.73534401  9.19238816
  10.          9.19238816  9.89949494 15.55634919]
 [ 6.83330942  4.47213595  3.57137466  6.22711194  3.77134948  3.53553391
   4.         12.02081528  4.24264069  9.89949494]
 [ 4.77247007  3.57770876  4.39553805  0.          0.1754116   1.41421356
   8.          1.41421356  0.70710678  4.94974747]
 [ 6.83330942  2.23606798  8.92843666  2.28035085  3.50823208  1.41421356
  13.          2.82842712  2.12132034  7.77817459]
 [10.30419675  3.13049517  2.60985072  3.50823208  0.52623481  0.
   3.         18.38477631  0.70710678  6.36396103]
 [ 5.5317

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

In [218]:
z=np.arange(1,15,dtype=np.uint32)
r=stride_tricks.as_strided(z,(11,4),(4,4))
print(r)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


#### 82. Compute a matrix rank (★★★)

In [223]:
m=np.random.randint(-10,10,(3,3))
print(m)
u,s,v= np.linalg.svd(m) 
rank = np.sum(s>=0)
print(rank)

[[ -1  -3  -9]
 [  5   7  -4]
 [  6 -10   2]]
3


#### 83. How to find the most frequent value in an array?

In [226]:
w=np.random.randint(0,10,10)
print(w,np.bincount(w).argmax())

[6 6 6 2 9 1 3 0 5 7] 6


#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

In [227]:
q=np.random.randint(0,100,(10,10))
i = 1 + (q.shape[0]-3)
j = 1 + (q.shape[1]-3)
C = stride_tricks.as_strided(q,shape=(i, j,3,3), strides=q.strides + q.strides)
print(C)

[[[[57  1 88]
   [94 22 46]
   [16 43 51]]

  [[ 1 88 79]
   [22 46 66]
   [43 51 67]]

  [[88 79  8]
   [46 66 14]
   [51 67 17]]

  [[79  8 89]
   [66 14 43]
   [67 17 68]]

  [[ 8 89 84]
   [14 43 77]
   [17 68 48]]

  [[89 84  7]
   [43 77 54]
   [68 48 66]]

  [[84  7  7]
   [77 54 81]
   [48 66  7]]

  [[ 7  7 61]
   [54 81 81]
   [66  7 11]]]


 [[[94 22 46]
   [16 43 51]
   [85 23 63]]

  [[22 46 66]
   [43 51 67]
   [23 63  8]]

  [[46 66 14]
   [51 67 17]
   [63  8 83]]

  [[66 14 43]
   [67 17 68]
   [ 8 83 89]]

  [[14 43 77]
   [17 68 48]
   [83 89 11]]

  [[43 77 54]
   [68 48 66]
   [89 11 58]]

  [[77 54 81]
   [48 66  7]
   [11 58 69]]

  [[54 81 81]
   [66  7 11]
   [58 69 90]]]


 [[[16 43 51]
   [85 23 63]
   [28 70 92]]

  [[43 51 67]
   [23 63  8]
   [70 92 54]]

  [[51 67 17]
   [63  8 83]
   [92 54 43]]

  [[67 17 68]
   [ 8 83 89]
   [54 43 15]]

  [[17 68 48]
   [83 89 11]
   [43 15 49]]

  [[68 48 66]
   [89 11 58]
   [15 49 76]]

  [[48 66  7]
   [11 58 69]


#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

In [45]:
class Symetric(np.ndarray):
    def __setitem__(self, index, value):
        i,j = index
        super(Symetric, self).__setitem__((i,j), value)
        super(Symetric, self).__setitem__((j,i), value)

def symetric(Z):
    return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)

S = symetric(np.random.randint(0,10,(5,5)))
S[2,3] = 42
print(S)

[[ 8 11  8 12 10]
 [11  6  7  6  6]
 [ 8  7  7 42  9]
 [12  6 42  3  7]
 [10  6  9  7  5]]


#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

In [44]:
p, n =4, 20
M = np.ones((p,n,n))
V = np.ones((p,n,1))
S = np.tensordot(M, V, axes=[[0, 2], [0, 1]])
print(S)

[[80.]
 [80.]
 [80.]
 [80.]
 [80.]
 [80.]
 [80.]
 [80.]
 [80.]
 [80.]
 [80.]
 [80.]
 [80.]
 [80.]
 [80.]
 [80.]
 [80.]
 [80.]
 [80.]
 [80.]]


#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

In [42]:
a=np.arange(16*16).reshape((16,16))
k=np.add.reduceat(np.add.reduceat(a,np.arange(0,a.shape[0],4), axis=0),np.arange(0,a.shape[1],4), axis=1)
print(k)

[[ 408  472  536  600]
 [1432 1496 1560 1624]
 [2456 2520 2584 2648]
 [3480 3544 3608 3672]]


#### 88. How to implement the Game of Life using numpy arrays? (★★★)

In [40]:
def iterate(Z):
    N = (Z[0:-2,0:-2] + Z[0:-2,1:-1] + Z[0:-2,2:] +
         Z[1:-1,0:-2]                + Z[1:-1,2:] +
         Z[2:  ,0:-2] + Z[2:  ,1:-1] + Z[2:  ,2:])
    birth = (N==3) & (Z[1:-1,1:-1]==0)
    survive = ((N==2) | (N==3)) & (Z[1:-1,1:-1]==1)
    Z[...] = 0
    Z[1:-1,1:-1][birth | survive] = 1
    return Z
Z = np.random.randint(0,2,(50,50))
for i in range(100): Z = iterate(Z)
print(Z)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


#### 89. How to get the n largest values of an array (★★★)

In [3]:
w=np.random.randint(0,100,10)
n=np.random.randint(0,10)
print(w,w[np.argsort(w)[n:]])

[28 42 24 31 68 50 73 19 72 99] [73 99]


#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

In [39]:
def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)
    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T
    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]
    return ix
print (cartesian(([1, 2, 3], [4, 5], [6, 7])))

[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


#### 91. How to create a record array from a regular array? (★★★)

In [38]:
r=np.array([("ARMY", 2013, 7),("BTS", 13, 6)])
R=np.core.records.fromarrays(r.T,names='col1, col2, col3',formats = 'S8, f8, i8')
print(R)

[(b'ARMY', 2013., 7) (b'BTS',   13., 6)]


#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

In [30]:
Z=np.random.rand(int(5e7))
%timeit np.power(Z,3)
%timeit Z*Z*Z
%timeit np.einsum('i,i,i->i',Z,Z,Z)

The slowest run took 6.87 times longer than the fastest. This could mean that an intermediate result is being cached.
7.27 s ± 7.62 s per loop (mean ± std. dev. of 7 runs, 1 loop each)
The slowest run took 8.48 times longer than the fastest. This could mean that an intermediate result is being cached.
1.29 s ± 1.53 s per loop (mean ± std. dev. of 7 runs, 1 loop each)
358 ms ± 39.3 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

In [29]:
A=np.random.randint(0,5,(8,3))
B=np.random.randint(0,5,(2,2))
C=(A[..., np.newaxis, np.newaxis]==B)
rows=np.where(C.any((3,1)).all(1))[0]
print(rows)

[0 3 4 6]


#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

In [28]:
f=np.random.randint(1,3,(10,3))
print(f)
e=f[f.max(axis=1)!=f.min(axis=1),:]
print(e)

[[2 1 1]
 [1 2 2]
 [1 1 1]
 [1 2 2]
 [1 2 1]
 [2 2 1]
 [2 1 2]
 [2 1 2]
 [1 1 2]
 [1 2 2]]
[[2 1 1]
 [1 2 2]
 [1 2 2]
 [1 2 1]
 [2 2 1]
 [2 1 2]
 [2 1 2]
 [1 1 2]
 [1 2 2]]


#### 95. Convert a vector of ints into a matrix binary representation (★★★)

In [24]:
v=np.random.randint(1,30,10,dtype=np.uint8)
print(v,np.unpackbits(v[:, np.newaxis], axis=1))

[ 6  2 16 22 17 23 15 12 17 19] [[0 0 0 0 0 1 1 0]
 [0 0 0 0 0 0 1 0]
 [0 0 0 1 0 0 0 0]
 [0 0 0 1 0 1 1 0]
 [0 0 0 1 0 0 0 1]
 [0 0 0 1 0 1 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 0 1 1 0 0]
 [0 0 0 1 0 0 0 1]
 [0 0 0 1 0 0 1 1]]


#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

In [22]:
s=np.random.randint(1,3,(20,4))
print(np.unique(s,axis=0))

[[1 1 1 1]
 [1 1 1 2]
 [1 1 2 1]
 [1 1 2 2]
 [1 2 1 2]
 [1 2 2 2]
 [2 1 1 1]
 [2 1 2 1]
 [2 1 2 2]
 [2 2 1 2]
 [2 2 2 1]
 [2 2 2 2]]


#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

In [15]:
A = np.random.randint(0,15,10)
B = np.random.randint(0,15,10)
np.einsum('i->', A)    
np.einsum('i,i->i', A, B) 
np.einsum('i,i', A, B)    
np.einsum('i,j->ij', A, B)   

array([[132, 132,  36, 144, 156,  60,  84,  96,  60,  60],
       [ 99,  99,  27, 108, 117,  45,  63,  72,  45,  45],
       [143, 143,  39, 156, 169,  65,  91, 104,  65,  65],
       [154, 154,  42, 168, 182,  70,  98, 112,  70,  70],
       [ 88,  88,  24,  96, 104,  40,  56,  64,  40,  40],
       [ 44,  44,  12,  48,  52,  20,  28,  32,  20,  20],
       [ 99,  99,  27, 108, 117,  45,  63,  72,  45,  45],
       [110, 110,  30, 120, 130,  50,  70,  80,  50,  50],
       [ 44,  44,  12,  48,  52,  20,  28,  32,  20,  20],
       [143, 143,  39, 156, 169,  65,  91, 104,  65,  65]])

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

In [12]:
phi = np.arange(0, 10*np.pi, 0.1)
a = 1
x = a*phi*np.cos(phi)
y = a*phi*np.sin(phi)
dr = (np.diff(x)**2 + np.diff(y)**2)**.5
r = np.zeros_like(x)
r[1:] = np.cumsum(dr)           
r_int = np.linspace(0, r.max(), 200) 
x_int = np.interp(r_int, r, x)       
y_int = np.interp(r_int, r, y)

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

In [10]:
X=np.asarray([[1.0, 0.0, 3.0, 8.0],
                [2.0, 0.0, 1.0, 1.0],
                [1.5, 2.5, 1.0, 0.0]])
n=4
M=np.logical_and.reduce(np.mod(X, 1) == 0, axis=-1)
M&=(X.sum(axis=-1) == n)
print(X[M])

[[2. 0. 1. 1.]]


#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)

In [9]:
X=np.random.randn(100)
N=1000
idx=np.random.randint(0, X.size, (N, X.size))
means=X[idx].mean(axis=1)
ci=np.percentile(means, [2.5, 97.5])
print(ci)

[-0.31575403  0.08280195]
